require('enyo/options').accessibility = true;

var
	ready = require('enyo/ready'),
	Sample = require('./src/All'),
	samples = {
		AccessibilitySample					: require('./src/AccessibilitySample'),
		AccordionSample						: require('./src/AccordionSample'),
		ActivityPanelsSample				: require('./src/ActivityPanelsSample'),
		ActivityPanelsWithVideoSample		: require('./src/ActivityPanelsWithVideoSample'),
		AlwaysViewingPanelsSample			: require('./src/AlwaysViewingPanelsSample'),
		AlwaysViewingPanelsWithVideoSample	: require('./src/AlwaysViewingPanelsWithVideoSample'),
		AnimatedButtonSample				: require('./src/AnimatedButtonSample'),
		AudioPlaybackSample					: require('./src/AudioPlaybackSample'),
		AudioPlaybackPlaylistSupportSample	: require('./src/AudioPlaybackPlaylistSupportSample'),
		BodyTextSample						: require('./src/BodyTextSample'),
		ButtonSample						: require('./src/ButtonSample'),
		CalendarSample						: require('./src/CalendarSample'),
		CheckboxItemSample					: require('./src/CheckboxItemSample'),
		ClockSample							: require('./src/ClockSample'),
		ContextualPopupSample				: require('./src/ContextualPopupSample'),
		DataGridListSample					: require('./src/DataGridListSample'),
		DataListSample						: require('./src/DataListSample'),
		DatePickerSample					: require('./src/DatePickerSample'),
		DialogSample						: require('./src/DialogSample'),
		DividerSample						: require('./src/DividerSample'),
		DrawerSample						: require('./src/DrawerSample'),
		DynamicPanelsSample					: require('./src/DynamicPanelsSample'),
		ExpandableDataPickerSample			: require('./src/ExpandableDataPickerSample'),
		ExpandableInputSample				: require('./src/ExpandableInputSample'),
		ExpandableListItemSample			: require('./src/ExpandableListItemSample'),
		ExpandablePickerSample				: require('./src/ExpandablePickerSample'),
		ExpandableTextSample				: require('./src/ExpandableTextSample'),
		FontSample							: require('./src/FontSample'),
		FormCheckboxSample					: require('./src/FormCheckboxSample'),
		HeaderSample						: require('./src/HeaderSample'),
		HighlightTextSample					: require('./src/HighlightTextSample'),
		HistorySample						: require('./src/HistorySample'),
		IconButtonSample					: require('./src/IconButtonSample'),
		IconSample							: require('./src/IconSample'),
		ImageBadgeSample					: require('./src/ImageBadgeSample'),
		ImageItemSample						: require('./src/ImageItemSample'),
		ImageSample							: require('./src/ImageSample'),
		InputHeaderSample					: require('./src/InputHeaderSample'),
		InputSample							: require('./src/InputSample'),
		IntegerPickerSample					: require('./src/IntegerPickerSample'),
		ItemSample							: require('./src/ItemSample'),
		ItemOverlaySample					: require('./src/ItemOverlaySample'),
		LabeledTextItemSample				: require('./src/LabeledTextItemSample'),
		LightPanelsSample					: require('./src/LightPanelsSample'),
		ListActionsSample					: require('./src/ListActionsSample'),
		MarqueeSample						: require('./src/MarqueeSample'),
		NewDataListSample					: require('./src/NewDataListSample'),
		ObjectActionHorizontalTypeSample	: require('./src/ObjectActionHorizontalTypeSample'),
		ObjectActionVerticalTypeSample		: require('./src/ObjectActionVerticalTypeSample'),
		OverlaySample						: require('./src/OverlaySample'),
		PanelsVideoPlayerSample				: require('./src/PanelsVideoPlayerSample'),
		PanelsWithCardArrangerSample		: require('./src/PanelsWithCardArrangerSample'),
		PanelsWithCarouselArrangerSample	: require('./src/PanelsWithCarouselArrangerSample'),
		PopupSample							: require('./src/PopupSample'),
		ProgressButtonSample				: require('./src/ProgressButtonSample'),
		ProgressSample						: require('./src/ProgressSample'),
		RadioItemSample						: require('./src/RadioItemSample'),
		Scroller2dSample					: require('./src/Scroller2dSample'),
		ScrollerHorizontalSample			: require('./src/ScrollerHorizontalSample'),
		ScrollerTextSample					: require('./src/ScrollerTextSample'),
		ScrollerVerticalSample				: require('./src/ScrollerVerticalSample'),
		SelectableItemSample				: require('./src/SelectableItemSample'),
		SimpleIntegerPickerSample			: require('./src/SimpleIntegerPickerSample'),
		SimplePickerSample					: require('./src/SimplePickerSample'),
		SliderSample						: require('./src/SliderSample'),
		SpinnerSample						: require('./src/SpinnerSample'),
		TableSample							: require('./src/TableSample'),
		TimePickerSample					: require('./src/TimePickerSample'),
		ToggleButtonSample					: require('./src/ToggleButtonSample'),
		ToggleItemSample					: require('./src/ToggleItemSample'),
		TooltipSample						: require('./src/TooltipSample'),
		VideoPlayerInlineSample				: require('./src/VideoPlayerInlineSample'),
		VideoPlayerSample					: require('./src/VideoPlayerSample')
	};

Sample.samples = samples;

ready(function() {
	new Sample().renderInto(document.body);
});

